"""
library.py
----------
Static stretch library parsed from stretches.csv data.

Exports:
  STRETCH_LIBRARY  : list of stretch dicts
  fallback_stretches() : returns five safe default stretches for error handling
"""

STRETCH_LIBRARY = [
    {
        "id": "S01",
        "name": "Neck Side Tilt",
        "target_muscle": "Sternocleidomastoid",
        "duration_seconds": 30,
        "posture_tags": ["neck", "forward_head"],
        "pain_keywords": ["neck pain", "stiff neck", "headache"],
        "steps": [
            "Sit up straight and relax your shoulders.",
            "Slowly tilt your right ear toward your right shoulder until you feel a gentle stretch on the left side of your neck.",
            "Hold for 30 seconds then repeat on the other side.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Sit facing the camera so it can see your head tilt to each side.",
        "difficulty": "Easy",
        "emoji": "🧘",
    },
    {
        "id": "S02",
        "name": "Neck Forward Nod",
        "target_muscle": "Suboccipital Muscles",
        "duration_seconds": 25,
        "posture_tags": ["neck", "forward_head"],
        "pain_keywords": ["neck tension", "text neck", "headache"],
        "steps": [
            "Sit tall with your shoulders relaxed and feet flat on the floor.",
            "Gently tuck your chin toward your chest as if making a double chin.",
            "Hold the position and breathe slowly for 25 seconds.",
        ],
        "camera_angle": "side",
        "camera_instruction": "Sit with your right side facing the camera so it can see your chin tuck and neck curve.",
        "difficulty": "Easy",
        "emoji": "😌",
    },
    {
        "id": "S03",
        "name": "Neck Rotation Stretch",
        "target_muscle": "Cervical Rotators",
        "duration_seconds": 30,
        "posture_tags": ["neck", "forward_head"],
        "pain_keywords": ["stiff neck", "neck tightness", "limited range"],
        "steps": [
            "Sit upright with your shoulders down and back.",
            "Slowly turn your head to the right as far as is comfortable without pain.",
            "Hold 15 seconds then turn to the left and hold 15 seconds.",
        ],
        "camera_angle": "standing_front",
        "camera_instruction": "Stand facing the camera so it can verify your head rotation is even on both sides.",
        "difficulty": "Easy",
        "emoji": "🔄",
    },
    {
        "id": "S04",
        "name": "Upper Trap Stretch",
        "target_muscle": "Upper Trapezius",
        "duration_seconds": 30,
        "posture_tags": ["neck", "shoulder"],
        "pain_keywords": ["neck pain", "shoulder tension", "headache"],
        "steps": [
            "Sit straight and hold the edge of your chair seat with your right hand.",
            "Tilt your left ear toward your left shoulder and place your left hand lightly on top of your head.",
            "Hold 30 seconds then switch sides.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Sit facing the camera so it can see your head tilt and confirm your shoulder stays down.",
        "difficulty": "Easy",
        "emoji": "💆",
    },
    {
        "id": "S05",
        "name": "Sky Gazer Stretch",
        "target_muscle": "Anterior Neck (SCM & Scalenes)",
        "duration_seconds": 20,
        "posture_tags": ["neck", "forward_head"],
        "pain_keywords": ["neck stiffness", "morning neck pain", "fatigue"],
        "steps": [
            "Sit tall with shoulders relaxed and hands resting on your thighs.",
            "Slowly tilt your head back until you are looking straight up at the ceiling.",
            "Keep your mouth closed and jaw relaxed — hold this position for 20 seconds.",
        ],
        "camera_angle": "side",
        "camera_instruction": "Sit with your side facing the camera so it can track the tilt of your head.",
        "difficulty": "Easy",
        "emoji": "🌤️",
    },
    {
        "id": "S06",
        "name": "Shoulder Roll",
        "target_muscle": "Deltoid and Trapezius",
        "duration_seconds": 20,
        "posture_tags": ["shoulder", "upper_back"],
        "pain_keywords": ["shoulder tightness", "hunched shoulders", "rounded shoulders"],
        "steps": [
            "Sit or stand tall with your arms resting at your sides.",
            "Roll both shoulders up toward your ears then backward and down in a smooth circle.",
            "Continue rolling slowly for 20 seconds.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Face the camera with both shoulders in frame; arms can stay at your sides — the tracker follows shoulder motion.",
        "difficulty": "Easy",
        "emoji": "🔁",
    },
    {
        "id": "S07",
        "name": "Doorway Chest Opener",
        "target_muscle": "Pectoralis Major",
        "duration_seconds": 30,
        "posture_tags": ["chest", "shoulder"],
        "pain_keywords": ["tight chest", "rounded shoulders", "poor posture"],
        "steps": [
            "Stand next to your desk and raise both arms to shoulder height with elbows bent at 90 degrees.",
            "Gently press your hands and forearms backward as if pushing against a doorframe.",
            "Hold the open position for 30 seconds and breathe deeply.",
        ],
        "camera_angle": "standing_front",
        "camera_instruction": "Stand facing the camera with arms raised so it can see your chest opening and elbows at shoulder level.",
        "difficulty": "Easy",
        "emoji": "🚪",
    },
    {
        "id": "S08",
        "name": "Seated Shoulder Squeeze",
        "target_muscle": "Rhomboids",
        "duration_seconds": 25,
        "posture_tags": ["shoulder", "upper_back"],
        "pain_keywords": ["upper back pain", "rounded shoulders", "shoulder blade pain"],
        "steps": [
            "Sit up straight with feet flat and hands resting on your thighs.",
            "Draw both shoulder blades toward each other as if trying to hold a pencil between them.",
            "Hold the squeeze for 25 seconds then slowly release.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Sit facing the camera so it can confirm both shoulder blades are moving equally.",
        "difficulty": "Easy",
        "emoji": "💪",
    },
    {
        "id": "S09",
        "name": "Cross-Body Shoulder Stretch",
        "target_muscle": "Posterior Deltoid",
        "duration_seconds": 30,
        "posture_tags": ["shoulder", "upper_back"],
        "pain_keywords": ["shoulder soreness", "tight shoulders", "back of shoulder pain"],
        "steps": [
            "Sit or stand and bring your right arm straight across your chest at shoulder height.",
            "Use your left hand to gently pull your right arm closer to your body.",
            "Hold 30 seconds then switch arms.",
        ],
        "camera_angle": "standing_side",
        "camera_instruction": "Stand with your right side facing the camera so it can see your arm crossing your body at the correct height.",
        "difficulty": "Easy",
        "emoji": "🤗",
    },
    {
        "id": "S10",
        "name": "Chest Stretch Arms Back",
        "target_muscle": "Pectoralis Minor",
        "duration_seconds": 25,
        "posture_tags": ["chest", "shoulder", "upper_back"],
        "pain_keywords": ["tight chest", "forward shoulders", "breathing tension"],
        "steps": [
            "Stand up straight and clasp your hands behind your lower back.",
            "Gently straighten your arms and lift your hands slightly while squeezing your shoulder blades together.",
            "Hold the stretch for 25 seconds.",
        ],
        "camera_angle": "standing_side",
        "camera_instruction": "Stand with your side facing the camera so it can see your arms behind your back and your chest lifting forward.",
        "difficulty": "Easy",
        "emoji": "🌟",
    },
    {
        "id": "S11",
        "name": "Seated Spinal Twist",
        "target_muscle": "Obliques and Spinal Rotators",
        "duration_seconds": 30,
        "posture_tags": ["spine", "lower_back"],
        "pain_keywords": ["lower back stiffness", "back pain", "spine tightness"],
        "steps": [
            "Sit tall on your chair with feet flat on the floor.",
            "Place your right hand on the back of the chair and your left hand on your right knee then twist gently to the right.",
            "Hold 30 seconds then repeat twisting to the left.",
        ],
        "camera_angle": "side",
        "camera_instruction": "Sit with your side facing the camera so it can see the full rotation of your spine.",
        "difficulty": "Easy",
        "emoji": "🌀",
    },
    {
        "id": "S12",
        "name": "Seated Side Stretch",
        "target_muscle": "Latissimus Dorsi and Obliques",
        "duration_seconds": 30,
        "posture_tags": ["spine", "upper_back", "shoulder"],
        "pain_keywords": ["side tightness", "lat pain", "trunk stiffness", "rib tightness"],
        "steps": [
            "Sit tall with feet flat on the floor and both hands resting on your thighs.",
            "Raise your right arm straight up overhead then lean your upper body gently to the left until you feel a stretch along your right side.",
            "Hold for 15 seconds then switch arms and lean to the right for another 15 seconds.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Sit facing the camera so it can see your raised arm and the lateral lean of your torso.",
        "difficulty": "Easy",
        "emoji": "🙆",
    },
    {
        "id": "S13",
        "name": "Seated Thoracic Extension",
        "target_muscle": "Thoracic Extensors",
        "duration_seconds": 30,
        "posture_tags": ["spine", "upper_back"],
        "pain_keywords": ["mid back stiffness", "upper back tightness", "thoracic pain", "hunching"],
        "steps": [
            "Sit tall at the edge of your chair with feet flat on the floor.",
            "Interlace your fingers and place both hands behind your head with elbows flared wide to the sides.",
            "Gently arch your upper back and lift your chest toward the ceiling, hold the position and breathe deeply for 30 seconds.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Sit facing the camera so it can see your elbows flared wide and your chest lifting.",
        "difficulty": "Easy",
        "emoji": "🏹",
    },
    {
        "id": "S14",
        "name": "Standing Back Extension",
        "target_muscle": "Lumbar Extensors",
        "duration_seconds": 20,
        "posture_tags": ["lower_back", "spine"],
        "pain_keywords": ["lower back ache", "prolonged sitting pain", "lumbar tightness"],
        "steps": [
            "Stand behind your chair and place your hands on the backrest for light support.",
            "Gently place your hands on your lower back and lean backward a small comfortable amount.",
            "Hold the extension for 20 seconds and breathe steadily.",
        ],
        "camera_angle": "standing_side",
        "camera_instruction": "Stand with your side facing the camera so it can see the backward arch in your lower back.",
        "difficulty": "Easy",
        "emoji": "🔙",
    },
    {
        "id": "S15",
        "name": "Seated Hamstring Stretch",
        "target_muscle": "Hamstrings",
        "duration_seconds": 30,
        "posture_tags": ["lower_back", "spine"],
        "pain_keywords": ["hamstring tightness", "back of leg pain", "sitting stiffness", "tight legs"],
        "steps": [
            "Sit tall at the edge of your chair with both feet flat on the floor.",
            "Extend your right leg straight out in front of you with your heel on the floor and toes pointing up.",
            "Hold the position for 30 seconds then switch to the left leg.",
        ],
        "camera_angle": "side",
        "camera_instruction": "Sit with your side facing the camera so it can see one leg extended straight and the other bent.",
        "difficulty": "Easy",
        "emoji": "🦵",
    },
    {
        "id": "S16",
        "name": "Wrist Flexor Stretch",
        "target_muscle": "Wrist Flexors",
        "duration_seconds": 25,
        "posture_tags": ["wrist", "forearm"],
        "pain_keywords": ["wrist pain", "typing pain", "carpal tunnel"],
        "steps": [
            "Extend your right arm straight in front of you with the palm facing up.",
            "Use your left hand to gently pull your right fingers downward toward the floor.",
            "Hold 25 seconds then switch to the other hand.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Hold your arm out toward the camera so it can see the angle of your wrist bend clearly.",
        "difficulty": "Easy",
        "emoji": "🤲",
    },
    {
        "id": "S17",
        "name": "Wrist Extensor Stretch",
        "target_muscle": "Wrist Extensors",
        "duration_seconds": 25,
        "posture_tags": ["wrist", "forearm"],
        "pain_keywords": ["wrist stiffness", "mouse hand pain", "forearm tightness"],
        "steps": [
            "Hold both arms out from your torso (a wide angle is OK — doesn’t have to be a perfect T). Hands do not need to touch.",
            "Arm 1 (either side): elbow fairly straight (~>152°) and wrist bent; detector is lenient on the exact bend.",
            "Arm 2: elbow reasonably open (~>118°); ignore wrist and hand — no contact required between hands.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Face the camera with hips in frame; both arms out from the body (they can stay apart).",
        "difficulty": "Easy",
        "emoji": "🖐️",
    },
    {
        "id": "S18",
        "name": "Seated Ankle Mobility",
        "target_muscle": "Ankles & lower calves",
        "duration_seconds": 25,
        "posture_tags": ["lower_body", "circulation", "desk"],
        "pain_keywords": ["swollen feet", "ankle stiffness", "long sitting", "leg fatigue"],
        "steps": [
            "Sit tall with feet under your knees and shoulders relaxed.",
            "Lift one heel so the foot clears the floor slightly; slowly circle the ankle in both directions.",
            "Place the foot down gently and repeat with the other side for the full duration.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Sit facing the camera with your lower legs and feet in frame so it can see one ankle lift clearly.",
        "difficulty": "Easy",
        "emoji": "🦶",
    },
    {
        "id": "S19",
        "name": "Prayer Stretch",
        "target_muscle": "Finger Flexors",
        "duration_seconds": 30,
        "posture_tags": ["wrist", "forearm"],
        "pain_keywords": ["finger stiffness", "wrist tension", "keyboard fatigue"],
        "steps": [
            "Press your palms together in a prayer position with fingers pointing up.",
            "Lower your joined hands to the middle of your torso (between upper chest and hips), keeping palms pressed.",
            "Hold for 30 seconds.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Face the camera with shoulders, hips, and hands visible; palms together around the central torso (not top or bottom quarter).",
        "difficulty": "Easy",
        "emoji": "🙏",
    },
    {
        "id": "S20",
        "name": "Finger Fan Stretch",
        "target_muscle": "Intrinsic Hand Muscles",
        "duration_seconds": 20,
        "posture_tags": ["wrist", "forearm"],
        "pain_keywords": ["finger pain", "stiff fingers", "hand fatigue"],
        "steps": [
            "Hold both hands out in front of you at chest height with palms facing away from you.",
            "Spread all your fingers as wide apart as possible like a fan.",
            "Hold the spread for 5 seconds then relax and repeat the fan motion slowly for 20 seconds total.",
        ],
        "camera_angle": "front",
        "camera_instruction": "Hold your hands up facing the camera so it can see all fingers spreading fully and evenly.",
        "difficulty": "Easy",
        "emoji": "🖐",
    },
]


def fallback_stretches() -> list:
    """Return 5 safe general stretches used when the AI recommendation fails."""
    fallback_ids = ["S05", "S04", "S15", "S11", "S11"]
    by_id = {s["id"]: s for s in STRETCH_LIBRARY}
    return [by_id[sid] for sid in fallback_ids if sid in by_id]
